name: "Run CI"

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Build TypeScript
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run Dependency Analysis
        run: npm run depcruise

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

      - name: Generate Dependency Graph
        run: npm run dependency-graph

      - name: Upload Dependency Graph
        uses: actions/upload-artifact@v3
        with:
          name: dependency-graph
          path: dependency-graph.svg
